name = "secureshare-backend"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
FRONTEND_URL = "https://secureshare-frontend-dev.pages.dev"
GOOGLE_CLIENT_ID = "99861091790-hfhln1sf4coagbpt15mm5v4hopbqu5dm.apps.googleusercontent.com"
GITHUB_CLIENT_ID = "Ov23lieHfdnNxJV0Rnfn"
SUPABASE_URL = "https://vorjuqvzwcjmwxkdthvz.supabase.co"
